### ISSUE TITLE
Photo row placeholder is showing behind the photos

### ISSUE THREAD

**Issue by matsimitsu** [daybreakers-co/frontend#16]
![daybreakers_](https://user-images.githubusercontent.com/28408/31739390-009440d0-b44e-11e7-927b-5fb9c1f5c6d1.png)

We can hide the placeholder once an image has been uploaded, or we could make sure it's always on top (with an opacity?), and show that on hover, for example:

![daybreakers_](https://user-images.githubusercontent.com/28408/31739470-49ed041a-b44e-11e7-8b0f-b6c663b08b66.png)

**Comment by wesoudshoorn** [comment]
Showing one on hover seems like a fine idea.
